# Generated by Django 5.2.5 on 2025-10-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cotizacion_detallecotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
