# Generated by Django 5.2.5 on 2025-11-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresaconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cai',
            name='prefijo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Prefijo SAR'),
        ),
    ]
