# Generated by Django 5.2.5 on 2025-11-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_venta_metodo_pago_alter_cai_prefijo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
    ]
