# Generated by Django 5.2.5 on 2025-11-25 06:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_recepcion',
            field=models.DateField(blank=True, help_text='Fecha en que se recibió la mercancía', null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='impuesto_15',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='impuesto_18',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones o notas adicionales'),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_compra',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_factura_proveedor',
            field=models.CharField(blank=True, max_length=50, verbose_name='# Factura Proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='subtotal_exento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='subtotal_g15',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal Gravado 15%'),
        ),
        migrations.AddField(
            model_name='compra',
            name='subtotal_g18',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal Gravado 18%'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento en porcentaje', max_digits=5),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, help_text='Nombre del contacto principal', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rtn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RTN'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.compra'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre/Razón Social'),
        ),
    ]
