# Generated by Django 5.2.7 on 2026-02-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_compra_options_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='isv_default',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=5),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='moneda',
            field=models.CharField(default='L', max_length=10),
        ),
    ]
