# Generated by Django 5.2.7 on 2026-02-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_empresaconfig_actualizado_empresaconfig_isv_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_ventas', models.BooleanField(default=True)),
                ('mod_cotizaciones', models.BooleanField(default=True)),
                ('mod_productos', models.BooleanField(default=True)),
                ('mod_compras', models.BooleanField(default=True)),
                ('mod_cuentas', models.BooleanField(default=True)),
                ('mod_empleados', models.BooleanField(default=True)),
                ('mod_cai', models.BooleanField(default=True)),
                ('mod_reportes', models.BooleanField(default=True)),
                ('mod_cierre_caja', models.BooleanField(default=False)),
            ],
        ),
    ]
