# Generated by Django 5.2.7 on 2026-02-08 18:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Caja Principal', max_length=60)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número de referencia o autorización', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CajaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_apertura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_otro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ingresos_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('egresos_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('efectivo_teorico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('efectivo_contado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('anulada', 'Anulada')], default='abierta', max_length=10)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.caja')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('concepto', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.cajasesion')),
            ],
        ),
    ]
