# Generated by Django 5.2.7 on 2026-02-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_caja_alter_pago_metodo_alter_pago_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduloconfig',
            name='mod_cierre_caja',
        ),
        migrations.AddField(
            model_name='moduloconfig',
            name='mod_caja',
            field=models.BooleanField(default=True),
        ),
    ]
