# Generated by Django 5.2.7 on 2026-02-12 16:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cai', '0001_initial'),
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_exento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_g15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_g18', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('impuesto_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('impuesto_18', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tipo_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('numero_factura', models.CharField(blank=True, max_length=30, null=True)),
                ('cai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cai.cai')),
                ('cliente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia o autorización', max_length=100, null=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_linea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
        ),
    ]
