# Generated by Django 5.2.7 on 2026-02-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('productos', '0002_alter_categoria_options_categoria_empresa_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
