# Generated by Django 5.2.7 on 2026-02-19 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ventas', '0002_pago_empresa_venta_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_ventas', to='core.empresa'),
            preserve_default=False,
        ),
    ]
