# Generated by Django 5.2.7 on 2026-02-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rtn', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('moneda', models.CharField(default='L', max_length=10)),
                ('isv_default', models.DecimalField(decimal_places=2, default=0.15, max_digits=5)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_ventas', models.BooleanField(default=True)),
                ('mod_cotizaciones', models.BooleanField(default=True)),
                ('mod_productos', models.BooleanField(default=True)),
                ('mod_compras', models.BooleanField(default=True)),
                ('mod_cuentas', models.BooleanField(default=True)),
                ('mod_empleados', models.BooleanField(default=True)),
                ('mod_cai', models.BooleanField(default=True)),
                ('mod_reportes', models.BooleanField(default=True)),
                ('mod_caja', models.BooleanField(default=True)),
            ],
        ),
    ]
