# Generated by Django 5.2.7 on 2026-02-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduloconfig',
            name='empresa',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduloconfig',
            name='mod_clientes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moduloconfig',
            name='mod_proveedores',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresaconfig',
            name='empresa',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.empresa'),
            preserve_default=False,
        ),
    ]
