# Generated by Django 5.2.7 on 2026-02-17 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('core', '0015_empresa_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='empresaconfig',
            name='correo',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
