# Generated by Django 5.2.7 on 2026-02-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='core.empresa'),
            preserve_default=False,
        ),
    ]
