# Generated by Django 5.2.7 on 2026-02-19 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoempleado',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_empleados', to='core.empresa'),
            preserve_default=False,
        ),
    ]
