# Generated by Django 5.2.7 on 2026-02-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=5, unique=True, verbose_name='Código o ID'),
        ),
    ]
