# Generated by Django 5.2.7 on 2026-02-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=5, verbose_name='Código o ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de barra'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_producto_codigo_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_barra'), name='uniq_producto_barra_por_empresa'),
        ),
    ]
