# Generated by Django 5.2.7 on 2026-02-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=5, unique=True, verbose_name='Código o ID'),
        ),
    ]
