# Generated by Django 5.2.7 on 2026-02-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cotizaciones', '0001_initial'),
        ('productos', '0002_alter_categoria_options_categoria_empresa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_cotizaciones', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
    ]
