# Generated by Django 5.2.7 on 2026-02-18 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cajamovimiento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='caja_movimientos', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cajasesion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='caja_sesiones', to='core.empresa'),
            preserve_default=False,
        ),
    ]
