# Generated by Django 5.2.7 on 2026-02-18 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_compras', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_compra',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_compra'), name='uniq_numero_compra_por_empresa'),
        ),
    ]
