# Generated by Django 5.2.7 on 2026-02-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código CAI')),
                ('prefijo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prefijo SAR')),
                ('rango_inicial', models.PositiveIntegerField(verbose_name='Correlativo inicial')),
                ('rango_final', models.PositiveIntegerField(verbose_name='Correlativo final')),
                ('correlativo_actual', models.PositiveIntegerField(verbose_name='Siguiente correlativo')),
                ('fecha_limite', models.DateField(verbose_name='Fecha límite de emisión')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
