# Generated by Django 5.2.7 on 2026-02-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cai', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cai',
            options={'ordering': ['-activo', 'fecha_limite']},
        ),
        migrations.AddField(
            model_name='cai',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cais', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cai',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código CAI'),
        ),
        migrations.AddConstraint(
            model_name='cai',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_cai_codigo_por_empresa'),
        ),
    ]
